version: '3.5'

services:
# API - transport
  api:
    build:
      context: .
    command: bash -c "npm install && npm start"
    depends_on:
      - nats
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: ${API_PORT}
    image: monolito-k8s-api
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=api"
      - "traefik.port=${API_PORT}"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"
    links:
      - nats
    restart: always
    volumes:
      - ./:/app
    working_dir: /app

  nats:
    image: nats
    restart: always
    ports:
      - ${NATS_PORT}:4222

  traefik:
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    image: traefik
    ports:
      - ${API_PORT}:80
      - ${TRAEFIK_PORT}:8080
    restart: always  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

# micro-services
  test:
    build:
      context: .
    command: bash -c "npm install && npm start"
    depends_on:
      - nats
    image: monolito_k8s_test
    env_file: docker-compose.env
    environment:
      SERVICES: test
    links:
     - nats
    restart: always
    volumes:
      - ./:/app
    working_dir: /app
